# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param synth.incrementalSynthesisCache ./.Xil/Vivado-660064-lorsi-ThinkPad-T490/incrSyn
set_param xicom.use_bs_reader 1
set_param tcl.collectionResultDisplayLimit 0
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir {/home/lorsi/Documents/CESE/CLP/VHDL-Sinewave-Generator/vivado/Sinewave Gen.cache/wt} [current_project]
set_property parent.project_path {/home/lorsi/Documents/CESE/CLP/VHDL-Sinewave-Generator/vivado/Sinewave Gen.xpr} [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:arty-z7-10:part0:1.0 [current_project]
set_property ip_output_repo {/home/lorsi/Documents/CESE/CLP/VHDL-Sinewave-Generator/vivado/Sinewave Gen.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  {/home/lorsi/Documents/CESE/CLP/VHDL-Sinewave-Generator/vivado/Sinewave Gen.srcs/sources_1/imports/components/button_counter.vhd}
  /home/lorsi/Documents/CESE/CLP/VHDL-Sinewave-Generator/src/components/generic_counter.vhd
  /home/lorsi/Documents/CESE/CLP/VHDL-Sinewave-Generator/src/components/sine_lut.vhd
  /home/lorsi/Documents/CESE/CLP/VHDL-Sinewave-Generator/src/sine_gen_top.vhd
}
read_ip -quiet {{/home/lorsi/Documents/CESE/CLP/VHDL-Sinewave-Generator/vivado/Sinewave Gen.srcs/sources_1/ip/buttons_vio/buttons_vio.xci}}
set_property used_in_implementation false [get_files -all {{/home/lorsi/Documents/CESE/CLP/VHDL-Sinewave-Generator/vivado/Sinewave Gen.srcs/sources_1/ip/buttons_vio/buttons_vio.xdc}}]
set_property used_in_implementation false [get_files -all {{/home/lorsi/Documents/CESE/CLP/VHDL-Sinewave-Generator/vivado/Sinewave Gen.srcs/sources_1/ip/buttons_vio/buttons_vio_ooc.xdc}}]

read_ip -quiet {{/home/lorsi/Documents/CESE/CLP/VHDL-Sinewave-Generator/vivado/Sinewave Gen.srcs/sources_1/ip/ila_0/ila_0.xci}}
set_property used_in_synthesis false [get_files -all {{/home/lorsi/Documents/CESE/CLP/VHDL-Sinewave-Generator/vivado/Sinewave Gen.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila_impl.xdc}}]
set_property used_in_implementation false [get_files -all {{/home/lorsi/Documents/CESE/CLP/VHDL-Sinewave-Generator/vivado/Sinewave Gen.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila_impl.xdc}}]
set_property used_in_implementation false [get_files -all {{/home/lorsi/Documents/CESE/CLP/VHDL-Sinewave-Generator/vivado/Sinewave Gen.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila.xdc}}]
set_property used_in_implementation false [get_files -all {{/home/lorsi/Documents/CESE/CLP/VHDL-Sinewave-Generator/vivado/Sinewave Gen.srcs/sources_1/ip/ila_0/ila_0_ooc.xdc}}]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/lorsi/Documents/CESE/CLP/VHDL-Sinewave-Generator/src/contraints/Arty-Z7-10-Master.xdc
set_property used_in_implementation false [get_files /home/lorsi/Documents/CESE/CLP/VHDL-Sinewave-Generator/src/contraints/Arty-Z7-10-Master.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top sinewave_gen_top -part xc7z010clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef sinewave_gen_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file sinewave_gen_top_utilization_synth.rpt -pb sinewave_gen_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
